CREATE TABLE user_sectors(
    id INT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    user_id INT,
    sector_id INT,
    CONSTRAINT fk_user
      FOREIGN KEY(user_id)
	  REFERENCES users(id),
	CONSTRAINT fk_sector
      FOREIGN KEY(sector_id)
	  REFERENCES sectors(id)
);